module(name = "go-tools")

http_archive = use_repo_rule("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

bazel_dep(name = "rules_cc", version = "0.0.2")
bazel_dep(name = "rules_foreign_cc", version = "0.12.0")
bazel_dep(name = "rules_rust", version = "0.63.0")

rust = use_extension("@rules_rust//rust:extensions.bzl", "rust")
rust.toolchain(
    edition = "2024",
    versions = ["1.85.0"],
)

http_archive(
    name = "katago",
    url = "https://github.com/lightvector/KataGo/archive/refs/tags/v1.16.3.zip",
    integrity = "sha256-qfcPsHaT2+/EzRB/56MDev/oTL3jo8d9qLHuA9AAnUI=",
    strip_prefix = "KataGo-1.16.3",
    patches = [
        "//third_party/katago/patches:001-MODULE.bazel.patch",
        "//third_party/katago/patches:002-BUILD.patch",
        "//third_party/katago/patches:003-cmake-install.patch",
        "//third_party/katago/patches:004-allow-initial-match-sgf.patch",
    ],
)

http_archive(
    name = "sgfutils",
    url = "https://github.com/yangboz/sgfutils/archive/11ab171c46cc16cc71ac6fc901d38ea88d6532a4.zip",
    integrity = "sha256-tayy753Ql7JCLKXiQuBZ7Gy4lP/2gwQHDlTjO/tAEKo=",
    strip_prefix = "sgfutils-11ab171c46cc16cc71ac6fc901d38ea88d6532a4",
    patches = [
        "//third_party/sgfutils/patches:001-MODULE.bazel.patch",
        "//third_party/sgfutils/patches:002-BUILD.patch",
    ],
)

crate = use_extension("@rules_rust//crate_universe:extensions.bzl", "crate")

crate.spec(package = "anyhow", version = "1.0.98")
crate.spec(package = "clap", version = "4", features = ["derive"])
crate.spec(package = "lazy-regex", version = "2.3.0")
crate.spec(package = "sgf-parse", version = "4.2.5")

crate.from_specs()
use_repo(crate, "crates")
